on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 12 * *" # At 03:30 on day-of-month 12

name: Open release PR

jobs:
  test:
    name: open-release-pr
    uses: kubewarden/github-actions/.github/workflows/reusable-release-pr.yml@cb97cbbcea106d12503c4b329f418cc406cb414a # v4.4.4
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
