on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      trigger_release:
        description: "Tag and trigger release manually"
        required: false
        default: true

name: Tag and Release on PR Merge

jobs:
  test:
    name: release-tag
    uses: kubewarden/github-actions/.github/workflows/reusable-release-tag.yml@cb97cbbcea106d12503c4b329f418cc406cb414a # v4.4.4
